version: "3.9"

services:
  hadoop:
    image: deadcoder11u2/hadoop-pack
    container_name: hadoop
    command: ["bash", "/entry-point.sh"]
    volumes:
      - ./conf/hadoop:/opt/hadoop/etc/hadoop
      - ./conf/hbase:/opt/hbase/conf
      - ./conf/pig:/opt/pig/conf
      - ./conf/hive:/opt/hive/conf
      - ./entry-point.sh:/entry-point.sh
